-- DoliCarbon - Reduction actions

CREATE TABLE llx_dolicarbon_action (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	fk_bilan integer NOT NULL,
	label varchar(255) NOT NULL,
	description text,
	category varchar(100),
	gain_tco2e_estimated double DEFAULT 0,
	gain_tco2e_actual double DEFAULT 0,
	cost_eur double DEFAULT 0,
	fk_user_responsible integer,
	date_deadline date,
	date_done date,
	status tinyint DEFAULT 0,
	fk_user_creat integer,
	date_creation datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	baseline_tco2e double DEFAULT 0,
	target_tco2e double DEFAULT 0,
	capex_eur double DEFAULT 0,
	opex_eur double DEFAULT 0,
	feasibility_score tinyint NULL,
	impact_score tinyint NULL,
	uncertainty_gain_low double NULL,
	uncertainty_gain_high double NULL,
	milestone_date date NULL,
	roadmap_quarter varchar(15) NULL,
	dependencies text NULL,
	evidence_done text NULL,
	is_fictional tinyint NOT NULL DEFAULT 0,
	seed_batch varchar(64) NULL
) ENGINE=innodb;
