-- One-time migration: rename legacy llx_const / llx_c_email_templates keys to doliprospectform (run once after deploy).
-- Run ONCE after deploying the new code and BEFORE or AFTER switching the module folder.
-- Replace llx_ with your Dolibarr table prefix if different (e.g. doli_const).

-- ---------------------------------------------------------------------------
-- llx_const: technical constants (MEGAWATTPARTNER_* → DOLIPROSPECTFORM_*)
-- ---------------------------------------------------------------------------
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_PUBLIC_FORM_SECRET' WHERE name = 'MEGAWATTPARTNER_PUBLIC_FORM_SECRET';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_TOKEN_VALIDITY_DAYS' WHERE name = 'MEGAWATTPARTNER_TOKEN_VALIDITY_DAYS';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_PUBLIC_DEFAULT_USER' WHERE name = 'MEGAWATTPARTNER_PUBLIC_DEFAULT_USER';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_PUBLIC_FORM_INDIVIDUAL' WHERE name = 'MEGAWATTPARTNER_PUBLIC_FORM_INDIVIDUAL';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_PUBLIC_FORM_PROFESSIONAL' WHERE name = 'MEGAWATTPARTNER_PUBLIC_FORM_PROFESSIONAL';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_INDIV_TITLE' WHERE name = 'MEGAWATTPARTNER_FORM_INDIV_TITLE';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_INDIV_INTRO' WHERE name = 'MEGAWATTPARTNER_FORM_INDIV_INTRO';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_INDIV_DOC_TITLE' WHERE name = 'MEGAWATTPARTNER_FORM_INDIV_DOC_TITLE';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_INDIV_DOC_HINT' WHERE name = 'MEGAWATTPARTNER_FORM_INDIV_DOC_HINT';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_PRO_TITLE' WHERE name = 'MEGAWATTPARTNER_FORM_PRO_TITLE';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_PRO_INTRO' WHERE name = 'MEGAWATTPARTNER_FORM_PRO_INTRO';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_PRO_DOC_TITLE' WHERE name = 'MEGAWATTPARTNER_FORM_PRO_DOC_TITLE';
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_FORM_PRO_DOC_HINT' WHERE name = 'MEGAWATTPARTNER_FORM_PRO_DOC_HINT';
UPDATE llx_const SET name = 'MAIN_SECURITY_ENABLECAPTCHA_DOLIPROSPECTFORM' WHERE name = 'MAIN_SECURITY_ENABLECAPTCHA_MEGAWATTPARTNER';
UPDATE llx_const SET name = 'MODULE_DOLIPROSPECTFORM_DISABLED' WHERE name = 'MODULE_MEGAWATTPARTNER_DISABLED';

-- Module activation flags (all MAIN_MODULE_MEGAWATTPARTNER* → DOLIPROSPECTFORM)
UPDATE llx_const SET name = REPLACE(name, 'MAIN_MODULE_MEGAWATTPARTNER', 'MAIN_MODULE_DOLIPROSPECTFORM') WHERE name LIKE 'MAIN_MODULE_MEGAWATTPARTNER%';

-- Optional: third-party numbering addon key if ever set
UPDATE llx_const SET name = 'DOLIPROSPECTFORM_MYOBJECT_ADDON' WHERE name = 'MEGAWATTPARTNER_MYOBJECT_ADDON';

-- ---------------------------------------------------------------------------
-- llx_c_email_templates: module code + substitution tags in body/topic
-- ---------------------------------------------------------------------------
UPDATE llx_c_email_templates SET module = 'doliprospectform' WHERE module = 'megawattpartner';

UPDATE llx_c_email_templates SET
  label = REPLACE(REPLACE(label, 'MegawattPartner', 'DoliProspectForm'), 'megawattpartner', 'doliprospectform'),
  topic = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(topic,
    '__MEGAWATTPARTNER_PUBLIC_LINK_HUB__', '__DOLIPROSPECTFORM_PUBLIC_LINK_HUB__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PARTICULIER__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PARTICULIER__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_INDIVIDUAL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_INDIVIDUAL__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PROFESSIONNEL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PROFESSIONNEL__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PROFESSIONAL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PROFESSIONAL__'),
    '__MEGAWATTPARTNER_PUBLIC_SALES_REP__', '__DOLIPROSPECTFORM_PUBLIC_SALES_REP__'),
  content = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(content,
    '__MEGAWATTPARTNER_PUBLIC_LINK_HUB__', '__DOLIPROSPECTFORM_PUBLIC_LINK_HUB__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PARTICULIER__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PARTICULIER__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_INDIVIDUAL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_INDIVIDUAL__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PROFESSIONNEL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PROFESSIONNEL__'),
    '__MEGAWATTPARTNER_PUBLIC_LINK_PROFESSIONAL__', '__DOLIPROSPECTFORM_PUBLIC_LINK_PROFESSIONAL__'),
    '__MEGAWATTPARTNER_PUBLIC_SALES_REP__', '__DOLIPROSPECTFORM_PUBLIC_SALES_REP__')
WHERE module = 'doliprospectform'
   OR topic LIKE '%__MEGAWATTPARTNER_%' OR content LIKE '%__MEGAWATTPARTNER_%';
